<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-11T11:50:33 IST" name="inetBankingV1" finished-at="2022-08-11T11:52:54 IST" duration-ms="141028">
    <groups>
    </groups>
    <test started-at="2022-08-11T11:50:33 IST" name="LoginTest1" finished-at="2022-08-11T11:52:54 IST" duration-ms="141028">
      <class name="com.inetBanking.testCases.TC_LoginTest_001">
        <test-method is-config="true" signature="intializeExtentReport()[pri:0, instance:com.inetBanking.testCases.TC_LoginTest_001@4135c3b]" started-at="2022-08-11T11:50:32 IST" name="intializeExtentReport" finished-at="2022-08-11T11:50:33 IST" duration-ms="1173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intializeExtentReport -->
        <test-method is-config="true" signature="setup(org.testng.ITestContext,java.lang.String)[pri:0, instance:com.inetBanking.testCases.TC_LoginTest_001@4135c3b]" started-at="2022-08-11T11:50:33 IST" name="setup" finished-at="2022-08-11T11:51:01 IST" duration-ms="27895" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@111c229c]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest()[pri:0, instance:com.inetBanking.testCases.TC_LoginTest_001@4135c3b]" started-at="2022-08-11T11:51:01 IST" name="loginTest" finished-at="2022-08-11T11:52:05 IST" duration-ms="64279" status="FAIL">
          <exception class="org.openqa.selenium.UnhandledAlertException">
            <message>
              <![CDATA[unexpected alert open: {Alert text : User is not valid}
  (Session info: MicrosoftEdge=104.0.1293.47): User is not valid
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'DESKTOP-EMOO80V', ip: '192.168.188.204', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [78ef093eb42b24071cde5aadd9cc6640, getTitle {}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 104.0.1293.47, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:51101}, msedge: {msedgedriverVersion: 104.0.1293.47 (246533a39fec..., userDataDir: C:\Users\Dell\AppData\Local...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51101/devtoo..., se:cdpVersion: 104.0.1293.47, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 78ef093eb42b24071cde5aadd9cc6640]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : User is not valid}
  (Session info: MicrosoftEdge=104.0.1293.47): User is not valid
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'DESKTOP-EMOO80V', ip: '192.168.188.204', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [78ef093eb42b24071cde5aadd9cc6640, getTitle {}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 104.0.1293.47, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:51101}, msedge: {msedgedriverVersion: 104.0.1293.47 (246533a39fec..., userDataDir: C:\Users\Dell\AppData\Local...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51101/devtoo..., se:cdpVersion: 104.0.1293.47, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 78ef093eb42b24071cde5aadd9cc6640
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:131)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:626)
at org.openqa.selenium.remote.RemoteWebDriver.getTitle(RemoteWebDriver.java:335)
at com.inetBanking.testCases.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.UnhandledAlertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="checkStatus(java.lang.reflect.Method,org.testng.ITestResult)[pri:0, instance:com.inetBanking.testCases.TC_LoginTest_001@4135c3b]" started-at="2022-08-11T11:52:05 IST" name="checkStatus" finished-at="2022-08-11T11:52:53 IST" duration-ms="47542" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.inetBanking.testCases.TC_LoginTest_001.loginTest()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=TC_LoginTest_001.loginTest()[pri:0, instance:com.inetBanking.testCases.TC_LoginTest_001@4135c3b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatus -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.inetBanking.testCases.TC_LoginTest_001@4135c3b]" started-at="2022-08-11T11:52:53 IST" name="TearDown" finished-at="2022-08-11T11:52:54 IST" duration-ms="1186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="generateExtentReport()[pri:0, instance:com.inetBanking.testCases.TC_LoginTest_001@4135c3b]" started-at="2022-08-11T11:52:54 IST" name="generateExtentReport" finished-at="2022-08-11T11:52:58 IST" duration-ms="3588" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateExtentReport -->
      </class> <!-- com.inetBanking.testCases.TC_LoginTest_001 -->
    </test> <!-- LoginTest1 -->
  </suite> <!-- inetBankingV1 -->
</testng-results>
